baseURL = "https://www.wittrup.me"
languageCode = "en-us"
title = "Christian Wittrup - wittrup.me"
theme ="hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]
googleAnalytics = "UA-169820698-1"

[Author]
    name = "Christian Wittrup"

[params]

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "Contact"
        url = "#contact"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/cvewi"

    [[params.links]]
        icon = "linkedin-in"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/christianwittrup/"

    [params.colors]
        background = "#498F77"
        foreground = "#B2DBCD"
        hover = "#1B4235"