baseURL = "https://www.wittrup.me"
languageCode = "en-us"
title = "Christian Wittrup - dad, husband, "
theme ="hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Christian Wittrup"

[params]

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:christian@vewi.dk"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/cvewi"

    [[params.links]]
        icon = "fa-linkedin-in"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/christianwittrup/"